[pytest]
# Directorios de búsqueda de pruebas. Pytest buscará archivos que coincidan
# con 'test_*.py' o '*_test.py' dentro del directorio 'tests'.
testpaths = 
    tests

# Opciones de Pytest.
# addopts: Define opciones a usar por defecto, como la verbosidad (-v) 
# y la configuración de cobertura (--cov).
addopts = -v --cov=src --cov-report=term-missing --strict-markers

# Indica qué prefijo deben tener los nombres de los archivos de prueba y las funciones.
python_files = test_*.py
python_classes = Test
python_functions = test_