[pytest]
# Directories to search for tests. Pytest will search for files matching
# 'test_*.py' or '*_test.py' inside the 'tests' directory.
testpaths = 
    tests

# Pytest Options.
# addopts: Defines options to use by default, such as verbosity (-v) 
# and coverage configuration (--cov).
addopts = -v --cov=src --cov-report=term-missing --strict-markers

# Indicates which prefix the names of test files and functions must have.
python_files = test_*.py
python_classes = Test
python_functions = test_